### ISSUE TITLE
CUDA 10.1 support for EMD?

### ISSUE THREAD

**Issue by justanhduc** [Colin97/MSN-Point-Cloud-Completion#1]
I successfully compiled EMD using CUDA 10.1 but I encountered some undefined symbol error. Does the code not support CUDA 10.1?

**Comment by Colin97** [comment]
Could you please provide more details? I have not tried CUDA 10.1.

**Comment by justanhduc** [comment]
Please find the full log [here](https://gist.github.com/justanhduc/25eb3938998c2b1235309433b268f6a1).
OS: Linux Ubuntu 16.04
Anaconda Python 3.7
CUDA 10.1
Device: TiTan X

**Comment by Colin97** [comment]
What's your Pytorch version?

**Comment by justanhduc** [comment]
I'm using 1.3.1.

**Comment by Colin97** [comment]
Yes, when I tried 1.3 there were some problems. Maybe you can try another PyTorch version. I am not sure what's wrong with PyTorch 1.3, but I found that there are some people facing similar problems recently.

**Comment by justanhduc** [comment]
Yeah i think it can be a temporary solution. Thanks anw the code is really helpful.
