### ISSUE TITLE
Transfer Learning

### ISSUE THREAD

**Issue by mactavish10** [Colin97/MSN-Point-Cloud-Completion#10]
Hello @Colin97 , I was wondering if there's a way to perform transfer learning on the model you provided? Also, could you elaborate on the data prep part? I'm using ply files of my own, not from ShapeNet.

**Comment by Colin97** [comment]
In order to train on your own dataset, you may need to:
1. use the [PCN code](https://github.com/wentaoyuan/pcn/tree/master/render) to generate the partial point cloud.
2. Denoise the partial point cloud.
3. Sample ground truth point cloud.

**Comment by mactavish10** [comment]
Is it necessary to use the PCN code for generating the partial point clouds? I have written a program of my own which generates randomly shaped holes in point clouds.

**Comment by Colin97** [comment]
I think it should also work if you retrain the network.

**Comment by mactavish10** [comment]
My dataset isn't big enough to train the model from scratch, which is why I wanted to opt for transfer learning or fine-tuning the pre-trained model.
