### ISSUE TITLE
Generalization capability

### ISSUE THREAD

**Issue by MartinSmeyer** [Colin97/MSN-Point-Cloud-Completion#15]
Just out of curiosity, have you tried training jointly on multiple categories and/or tested on unknown categories? 

Of course results would degrade, but would it still give meaningful results?

Thanks!

**Comment by Colin97** [comment]
Sorry, I have not tried that before. It's an interesting point, but I guess it's less likely for the model to transfer to a completely novel categories.

**Comment by MartinSmeyer** [comment]
Thanks a lot for your answer! 

What do you think about training jointly on multiple categories? In real-world/robotic scenarios, your method would be useful, but the number of categories is usually very large whereas shapes are often shared.

Nice work by the way!

**Comment by MartinSmeyer** [comment]
Just as a reference, this paper has a nice discussion about it:
https://arxiv.org/pdf/2006.15427.pdf

**Comment by Colin97** [comment]
Our model is trained on multiple (8) categories, but I guess generalizability may be hard for our model. Yes, there are some recent works taking this issue into account and my recent [work](http://cseweb.ucsd.edu/~mil070/projects/ECCV2020/paper.pdf) on learning-based mesh reconstruction also possesses strong generalizability.
