### ISSUE TITLE
EMD Normalisation

### ISSUE THREAD

**Issue by theodeprelle** [Colin97/MSN-Point-Cloud-Completion#16]
Hi Colin,

Awesome work ! 

I had a question regarding the normalisation of the point cloud for the EMD. Could you tell me why is it needed to normalise the coordinates between 0 and 1. What will happen if I don't do that ?

**Comment by Colin97** [comment]
In our code, we assume the distance between two points is smaller than 3. If you do not want to normalize the coordinates, you may need to modify this [line](https://github.com/Colin97/MSN-Point-Cloud-Completion/blob/c5f23a91d343f6a76d07f04a589d0294d456a293/emd/emd_cuda.cu#L146). Also the eps should be adjusted accordingly.

**Comment by theodeprelle** [comment]
Ok thanks for the tips !
