### ISSUE TITLE
How to modify the code to make EMD work with points of other dimensions?

### ISSUE THREAD

**Issue by gdwei** [Colin97/MSN-Point-Cloud-Completion#19]
Great work and thanks for sharing the code!

I am wondering how to modify your code to work with points in a 4 dim space, i.e. points with shape [#batch, #points, 4].

It seems that I only need to modify some lines in <emd_cuda.cu>, but since I do not fimilar with cuda programming at all, 

it will be appreciated if you can give me some detail advises!

**Comment by Colin97** [comment]
Yes, I also think you may need to modify 'emd_cudda.cu':
line 97 (you may want to decrease 'batch')
line 98, 120-122, 127-128, 142-144, 146, 221-223, 287-289, 291-293, 295-297.

**Comment by gdwei** [comment]
> Yes, I also think you may need to modify 'emd_cudda.cu':
> line 97 (you may want to decrease 'batch')
> line 98, 120-122, 127-128, 142-144, 146, 221-223, 287-289, 291-293, 295-297.

Thanks a lot.
