### ISSUE TITLE
Can the dimension of data larger than 3 to calculate emd?

### ISSUE THREAD

**Issue by datong-new** [Colin97/MSN-Point-Cloud-Completion#25]
Hello, thanks for your wonderful work!

If I have two sets of data whose dimensions are larger than 3. Can I still use your emd to calculate their distance?

``` python
x1 = torch.rand(20, 8192, 100).cuda()
x2 = torch.rand(20, 8192, 100).cuda()

emd = emdModule()
dis, assigment = emd(x1, x2, 0.05, 3000)
```

I have tested it and no error is reported. But I am not sure if it makes sense. Thanks! 

It seems that EMD and Verified EMD are different:

```
Input_size:  torch.Size([20, 8192, 100])
Runtime: 0.863681s
EMD: 0.046708
|set(assignment)|: 8192
Verified EMD: 4.075622
```

**Comment by Colin97** [comment]
No, existing code can be only applied to 3D point clouds. You may need to modify the CUDA code to extend to other dimensions. It is also not clear the performance of the algorithm under different dimensions.
