### ISSUE TITLE
About the dataset and the gpu.

### ISSUE THREAD

**Issue by qinglew** [Colin97/MSN-Point-Cloud-Completion#27]
It seems like that the partial point cloud dataset generated from ShapeNet is very large (up to 49 GB), so could you please give the information of the GPU you used in the experiment ShapeNet completion? Can we train the model with a general GPU?

**Comment by Colin97** [comment]
It's provided in the paper, we use 8 GPUS(1080Ti/2020Ti) to train the model (for several days).
