### ISSUE TITLE
Could you please give the python version and open3d version you used to generated the partial point cloud?

### ISSUE THREAD

**Issue by qinglew** [Colin97/MSN-Point-Cloud-Completion#28]
I try the code to generate the partial point clouds but got the failure. Could you please give more details about the environment for the code to generate the partial point clouds?

**Comment by Colin97** [comment]
What kind of failure? We follow the code of PCN to generate the partial point cloud. Sorry, I don't remember the version information.

**Comment by qinglew** [comment]
Thank you very much for your replying. In the render/process_exr.py, the Image, PointCloud, and Vector3dVector cannot be find. These classes can only be imported from the open3d, i.e., "from open3d import *", but these classes cannot be finded. So I just asked the version of the open3d.

**Comment by qinglew** [comment]
When I use the Python3.5, the error is blew:
```
Traceback (most recent call last):
  File "process_exr.py", line 31, in <module>
    from open3d import *
  File "/home/rico/anaconda3/envs/python35/lib/python3.5/site-packages/open3d/__init__.py", line 47, in <module>
    from open3d.open3d_pybind import camera
ImportError: /home/rico/anaconda3/envs/python35/lib/python3.5/site-packages/open3d/open3d_pybind.cpython-35m-x86_64-linux-gnu.so: undefined symbol: _PyThreadState_UncheckedGet
```

When I use a version higher than Python3.5, the error is:

```
Traceback (most recent call last):
  File "process_exr.py", line 79, in <module>
    depth_img = Image(np.uint16(depth * 1000))
NameError: name 'Image' is not defined
```

**Comment by Colin97** [comment]
I guess you may need to rewrite the code for the newest open3d version.
