### ISSUE TITLE
Image in the paper

### ISSUE THREAD

**Issue by Katrina-cmd** [Colin97/MSN-Point-Cloud-Completion#31]
Hello, how do you display the point cloud image in the paper? Can you publish your code?

**Comment by Colin97** [comment]
Please see #17 and #23.

**Comment by Katrina-cmd** [comment]
Thank you for your answer. At the same time, do you know what to render the point cloud in xyz format?

**Comment by Colin97** [comment]
Blender can also take xyz files as input.
