### ISSUE TITLE
comparing point clouds

### ISSUE THREAD

**Issue by david-ngo-sixense** [Colin97/MSN-Point-Cloud-Completion#32]
Thanks for your repository.
Do you think it is possible to use your code to calcule the distances between two point clouds ?
I have S_A and S_B are two point clouds sampled on the same surface (at two different time, the surface may be deformed or translated/rotated). 
And I want to calculate the distance between each point in S_B with the corresponding implicit surface of S_A (an example is a monitoring project to detect changes between two point clouds)
Thanks very much

**Comment by Colin97** [comment]
Yes, EMD can be used to calculate the distance between two point clouds. You can directly solve the matching problem if you don't need to calculate the distance as a deep learning loss.
