### ISSUE TITLE
3D modeling file .obj normalization method

### ISSUE THREAD

**Issue by swlee93-dev** [Colin97/MSN-Point-Cloud-Completion#33]
Hi, 
I have a question about .obj file normalization method.
I want to test your deep-learning model on my 3D modeling dataset.
But, I don't find method that normalize .obj file size x, y, z components like your dataset(ShapeNet).
If you know about it, tell me anything.
Thank you.

**Comment by Colin97** [comment]
You could try to load the models (using any 3D library) and then normalize the position of the vertices by yourself.
