### ISSUE TITLE
Cuda running out of memory

### ISSUE THREAD

**Issue by PieroSgri** [Colin97/MSN-Point-Cloud-Completion#34]
I'm running val.py on a windows machine with a Nvidia 1060 6GB VRAM and I get the following:

`RuntimeError: CUDA out of memory. Tried to allocate 1.56 GiB (GPU 0; 6.00 GiB total capacity; 2.12 GiB already allocated; 1.06 GiB free; 1.54 GiB cached)`

How much VRAM did you have on your system?

**Comment by Colin97** [comment]
I think it was 12GB. You may try a smaller batch size.
