### ISSUE TITLE
Can I ask how do you draw those beautiful point cloud pictures in teaser.png?

### ISSUE THREAD

**Issue by youkangGG** [Colin97/MSN-Point-Cloud-Completion#36]
Nothing's more refreshing than enjoying such a 3d models picture!

You also put some super nice point clouds in:
https://github.com/Colin97/MSN-Point-Cloud-Completion/blob/master/emd/CDEMD.png

I have seen similar point cloud images in some other papers, and I always wanted to know how to draw them. I would be very appreciate it if you could show it to me.

ヾ(≧▽≦*)o

**Comment by Colin97** [comment]
Please see #23. We use blender to render the paper figures.
