### ISSUE TITLE
Save the output

### ISSUE THREAD

**Issue by SimonNgj** [Colin97/MSN-Point-Cloud-Completion#38]
Do you have a function to save the point cloud output?

**Comment by Colin97** [comment]
You can use any 3d library (e.g., open3d) or directly "np.savetxt" (to xyz files).

**Comment by SimonNgj** [comment]
I don't think np.savetxt() works, bcz output1 and output2 are cuda tensor. Even when converting it to np array by output1.cpu().data.numpy(), they are 3D array. np.savetxt() only supports 1D or 2D array
