### ISSUE TITLE
asking about generating training data

### ISSUE THREAD

**Issue by AlphaPav** [Colin97/MSN-Point-Cloud-Completion#7]
Hi, 

After following the **render** process in https://github.com/wentaoyuan/pcn/tree/master/render, I can get those .pcd files, which should be the training data? Are there any other steps?

The completed data are provided in the google drive, so there is no need to follow the **sample** process in https://github.com/wentaoyuan/pcn/tree/master/sample?

Thank you!!

**Comment by Colin97** [comment]
There are no other steps.

You can use the completed data provided in the google drive.

**Comment by AlphaPav** [comment]
Thank you!

**Comment by Colin97** [comment]
Sorry, I just forgot to mention that there is an optional denoising step to remove the outliers. Please refer to #8.
