### ISSUE TITLE
Denoise the generated partial point cloud for training.

### ISSUE THREAD

**Issue by StevenZzz07** [Colin97/MSN-Point-Cloud-Completion#8]
Dear, 

Thanks for your outstanding work!

I have followed the render process in PCN, and obtained the partial point cloud from ShapeNet for training. However, I find that some of my results are a little noisy as follows:
![image](https://user-images.githubusercontent.com/56421441/76482419-0a867780-644f-11ea-89c9-194b5600de94.png)

And I notice the val data you provide is title as 'model_id/scan_id_denoised.pcd', so I am wondering whether there is a further denosing step to be taken to refine the generated partial data?

Have a good day!

**Comment by Colin97** [comment]
Yes, there is a further denoising step. Please refer to https://github.com/wentaoyuan/pcn/issues/21.

Specifically, I employ the radius_outlier_removal in open3d to remove the outliers.

`from open3d import *`
`denoised, ind = radius_outlier_removal(pc, nb_points=5, radius=0.03)`

**Comment by SarahChane98** [comment]
Hello @Colin97! Where should this snippet of code be placed? Should it be at the end of pcn/render/process_exr.py? Also, do you have any idea how OpenEXR can be installed for process_exr.py? Could you please offer some tips on its installation? Tried to build from source but failed... Thanks in advance!:)
